# Numpy Random Number Generation

In [4]:
import numpy as np

**Arrays With Random Floats**

In [10]:
a = np.random.rand(3) # size = 3
a

array([0.45255545, 0.45913695, 0.90004096])

**Multidimensional Arrays**

In [13]:
a = np.random.rand(3, 3)
a

array([[0.50778504, 0.80723085, 0.35785236],
       [0.8241404 , 0.70455733, 0.14269237],
       [0.44301609, 0.91960871, 0.26260861]])

**Random Integers in a Range:**

In [97]:
n1 = np.random.randint(-10, 10) # 10 is excluded upper bound: [-10, 10)
n1

-6

**Multidim Random Integers in Range**

In [118]:
n2 = np.random.randint(10, 100, (5, 5)) # range: [10, 100), size = (5, 5)
n2

array([[89, 76, 11, 71, 49],
       [92, 19, 97, 47, 55],
       [92, 54, 20, 38, 75],
       [20, 35, 41, 53, 86],
       [50, 81, 42, 66, 16]])

**Shuffling An Array:**
- By defaults shuffles the element in first axis.

In [123]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("Before Shuffling")
print(arr)

print("After Shuffling")
np.random.shuffle(arr)
print(arr)

Before Shuffling
[[1 2 3]
 [4 5 6]
 [7 8 9]]
After Shuffling
[[1 2 3]
 [4 5 6]
 [7 8 9]]


**Shuffling accross 2nd axis**

In [143]:
list(map(numpy.random.shuffle, arr))
arr

array([[2, 3, 1],
       [5, 4, 6],
       [8, 9, 7]])

**Reproducibility**

In [158]:
np.random.seed(1)

np.random.randint((2,2))

array([1, 1])

In [161]:
np.random.seed(1)

np.random.randint((2,2))

array([1, 1])